language: node_js

node_js:
- "5.9.1"

branches:
  only:
  - master

before_install:
#- npm install hexo@3.1.1 -g

install:
- npm install
#- npm install hexo-generator-feed --save

# Notice: Replace 'YOUR NAME' and 'YOUR EMAIL'
before_script:
- git config --global user.name 'codejuan'
- git config --global user.email 'xh@decbug.com'

script:
- pwd
- hexo version
- hexo clean
- hexo generate

after_success:
- mkdir .deploy
- cd .deploy
- git clone --depth 1 --branch gh-pages --single-branch $DEPLOY_REPO . || (git init && git remote add -t gh-pages origin $DEPLOY_REPO)
- rm -rf ./*
- cp -r ../public/* .
- cp ../CNAME .
- git add -A .
- git commit -m 'Site updated'
- git branch -m gh-pages
- git push -q -u origin gh-pages
