# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Continuous Learning
subtitle: 浮云一别后，流水十年间
description:
author: CodeJuan
language: zh-Hans
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: 'http://blog.decbug.com'
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
about_dir: about
book_dir: book
twitter_dir: twitter
test_dir: test
i18n_dir: :lang
skip_render:

# theme next
avatar: https://avatars3.githubusercontent.com/u/5423628?v=3&s=460
disqus_shortname: codejuan
google_analytics: UA-57346409-1
# Social links
social:
  github: https://github.com/codejuan
  twitter: https://twitter.com/decbug
  stackoverflow: http://stackoverflow.com/users/2763396/codejuan
  #weibo: http://weibo.com/your-user-name
  #douban: http://douban.com/people/your-user-name
  #zhihu: http://www.zhihu.com/people/your-user-name
links_title: Links
# links
links:
  decbug: http://blog.decbug.com/


# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 5
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
plugins:
 - hexo-generator-sitemap
 - hexo-generator-feed
# - hexo-tag-emojis
## Themes: http://hexo.io/themes/
theme: next
stylus:
  compress: true

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type:


# hexo-tag-emojis plugin configuration
#emojis:
#  image_dir: images/emojis
